#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function sanitizeName(name){
  return name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g,'') || 'note';
}

const title = process.argv[2];
const examplePath = process.argv[3];

if(!title){
  console.error('Usage: node create_note.js "Title of note" [path/to/example.js]');
  process.exit(1);
}

const fileName = sanitizeName(title) + '.md';
const dir = path.join(process.cwd(), 'IQ_Notes');
if(!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
const outPath = path.join(dir, fileName);

let exampleCode = '';
let exampleDisplayPath = '';
if(examplePath){
  const fullExample = path.isAbsolute(examplePath) ? examplePath : path.join(process.cwd(), examplePath);
  exampleDisplayPath = examplePath;
  try{
    exampleCode = fs.readFileSync(fullExample, 'utf8');
  }catch(e){
    exampleCode = `// Failed to read example at ${examplePath}\n`;
  }
}

const content = `# ${title}\n\n` +
`## Summary\n\nWrite a concise explanation of the concept here.\n\n` +
`## Example\n\n` + (exampleCode ? `Example file: ${exampleDisplayPath}\n\n` + '```js\n' + exampleCode + '\n```\n\n' : 'No example provided.\n\n') +
`## Comparison Table\n\n| Term | What it is | Example | Produced by / Run on |\n|---|---:|---|---|\n| Source code | Human-readable program text written by developers. | (example snippet) | Written by developer; fed to parser/compiler. |\n| Bytecode (intermediate) | Compact, VM-specific instructions (interpreted or fed to JIT). | (VM bytecode) | Generated by the engine's bytecode generator; executed by VM. |\n| Binary / Machine code | Native CPU instructions executed by the processor. | (assembly) | Produced by a compiler/JIT; executed on the CPU. |\n\n` +
`## Inspecting (Node / V8 examples)\n\n` +
'```\n' +
`node --print-bytecode ${examplePath || '<example.js>'}\n` +
`node --print-opt-code ${examplePath || '<example.js>'}  # advanced, may require flags\n` +
'```\n\n' +
`---\nGenerated by create_note.js
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Created:', outPath);
